{% set name = "zope.deferredimport" %}
{% set version = "5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3abbf0e18c1f1765914ecd1d41b549e4d045b21b28e4065fb0c1de0ad736b2c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - zope.proxy

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/zopefoundation/zope.deferredimport
  license: ZPL 2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: defers import to when objects are actually used
  description: |
    Often, especially for package modules, you want to import names for
    convenience, but not actually perform the imports until necessary.
    The zope.deferredimport package provided facilities for defining
    names in modules that will be imported from somewhere else when
    used. You can also cause deprecation warnings to be issued when a
    variable is used.
  doc_url: https://zopedeferredimport.readthedocs.io/
  dev_url: https://github.com/zopefoundation/zope.deferredimport

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
